app/urls.py
from django.contrib import admin
from django.urls import path, re_path
from .views import *
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

app_name = 'app'
urlpatterns = [
    path('', HomeView.as_view(), name='index'),
    path('login', auth, name='login'),
    path('load_more', get_more_tweets, name='load_more'),
    path('post', post_tweet, name='post_tweet'),
    path('search/', SearchView.as_view(), name='search'),
    path('hashtag/', HashtagView.as_view(), name='hashtag'),
    re_path(r'^settings/$', SettingView.as_view(), name='settings'),
    re_path(r'^json/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', get_tweet_json, name='get_tweet_json'),
    re_path(r'^detail/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', get_all_replies, name='get_detail'),
    re_path(r'^delete/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', delete_tweet, name='delete_tweet'),
    re_path(r'^fav/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', fav, name='fav_tweet'),
    re_path(r'^unfav/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', unfav, name='unfav_tweet'),
    re_path(r'^retweet/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', retweet, name='retweet'),
    re_path(r'^unretweet/(?P<tweet_id>[a-zA-Z0-9\-_]+)$', unretweet, name='unretweet'),
    re_path(r'^reply/(?P<reply_to>[a-zA-Z0-9\-_]+)$', reply, name='reply'),
    re_path(r'^follow/(?P<user_id>[a-zA-Z0-9\-_]+)$', follow, name='follow'),
    re_path(r'^unfollow/(?P<user_id>[a-zA-Z0-9\-_]+)$', unfollow, name='unfollow'),
    re_path(r'^(?P<username>[a-zA-Z0-9_]+)/$', UserPageView.as_view(), name='user_page'),
]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = []

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += (
        path('', include(debug_toolbar.urls)),
    )
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
]

app/models/tweet.py
from django.db import models
from django.conf import settings
import uuid as uuid_lib

class Tweet(models.Model):
    id = models.UUIDField(default=uuid_lib.uuid4,
                          primary_key=True, editable=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    content = models.CharField('内容', max_length=255)
    is_retweet = models.BooleanField('RT', default=False)
    reply_to = models.UUIDField('リプライ先', blank=True, null=True, default=None)
    created_at = models.DateTimeField('作成日時', auto_now_add=True)
    updated_at = models.DateTimeField('更新日時', auto_now=True)

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, UserManager
from django.contrib.auth.validators import UnicodeUsernameValidator
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
import uuid as uuid_lib
from django.conf import settings


from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.base_user import BaseUserManager

from app.models.follow import Follow

# Create your models here.

class CustomUserManager(UserManager):
    def get_queryset(self):
        return super().get_queryset().select_related('setting')

class User(AbstractBaseUser, PermissionsMixin):
    """ユーザー AbstractUserをコピペし編集"""

    id = models.UUIDField(default=uuid_lib.uuid4,
                            primary_key=True, editable=False)
    username_validator = UnicodeUsernameValidator()

    username = models.CharField(
        _('username'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    viewname = models.CharField(
        _('表示名'),
        max_length=150,
        unique=True,
        help_text=_(
            'Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.'),
        validators=[username_validator],
        error_messages={
            'unique': _("A user with that username already exists."),
        },
    )
    email = models.EmailField(_('email address'), blank=False)

    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_(
            'Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects =CustomUserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'viewname']

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)



class UserSetting(models.Model):
    """ユーザープロフィールモデル"""
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE,
                                related_name='setting', primary_key=True)
    picture = models.ImageField(upload_to='avatar_img', blank=True, null=True, )
    bio = models.TextField(blank=True)


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    """ 新ユーザー作成時に空のprofileも作成する """
    if kwargs['created']:
        user_profile = UserSetting.objects.get_or_create(user=kwargs['instance'])

user/views.py
from django.shortcuts import render

# Create your views here.

templates/app/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
          integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
            integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
            integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
            crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/6c0dfe6024.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'app/css/index.css' %}" type="text/css">

    <title>pakutter</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="#">pakutter</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'logout' %}">Log out</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="settings">Settings</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
        </div>
    </div>

</nav>
<div class="container">

    <div class="row">
        <div class="overlay ">
            <div class="alert alert-danger alert-dismissible rounded-bottom" id="alert" role="alert">
                <span id="alert-text">何かがおかしいようです。</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="閉じる">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        </div>
        <div class="col-3 mt-2">
            {% block left-column %}
            {% endblock %}
        </div>
        <div class="col-6 p-0 mt-2">


            {% block body %}
            {% endblock %}
        </div>
        <div class="hidden-lg-block col-xl-3 mt-2"></div>
    </div>

</div>
<script src="{% static 'app/js/index.js' %}"></script>
<script src="{% static 'app/js/endless_scroll.js' %}"></script>
</body>
</html>

templates/app/entry_list.html
<h2>Entries:</h2>
{% for entry in entry_list %}
    {# your code to show the entry #}
{% endfor %}

templates/app/home.html
{% extends "app/base.html" %}
{% load static %}
{% block body %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% include 'app/tweet_form.html' %}
    {% include 'app/time_line.html' %}

{% endblock %}

{% block left-column %}
<div class="card">
<ul>
    <li>
        {{ data.login_user.username }}
    </li>
    <li>
        フォローしている： {{ data.cnt_following }}
    </li>
    <li>
        フォローされている： {{ data.cnt_followed }}
    </li>
</ul>

</div>
{% endblock %}

templates/app/search.html
{% extends "app/base.html" %}
{% load static %}
{% block body %}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% include 'app/tweet_form.html' %}
    {% include 'app/time_line.html' %}

{% endblock %}

{% block left-column %}
<div class="card">
<ul>
    <li>
        {{ data.login_user.username }}
    </li>
    <li>
        フォローしている： {{ data.cnt_following }}
    </li>
    <li>
        フォローされている： {{ data.cnt_followed }}
    </li>
</ul>

</div>
{% endblock %}

templates/app/settings.html
{% extends "app/base.html" %}
{% load static %}

{% block left-column %}
    <div class="card">
        <ul>
            <li>
                {{ data.user.username }}
            </li>
            {% if data.login_user != data.user %}
                {% if not data.is_followed_by_login_user %}
                    <li>
                        <div class="user-id" hidden>{{ data.user.id }}</div>
                        <button class="follow-button">フォローする</button>
                    </li>
                {% else %}
                    <li>
                        <div class="user-id" hidden>{{ data.user.id }}</div>
                        <button class="follow-button followed">フォロー解除</button>
                    </li>
                {% endif %}
            {% endif %}
            <li>
                フォローしている： {{ data.cnt_following }}
            </li>
            <li>
                フォローされている： {{ data.cnt_followed }}
            </li>
        </ul>

    </div>
{% endblock %}

{% block body %}
    <form action="{% url 'app:settings' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ settingform.as_p }}
        {{ userform.as_p }}
        <input type="submit" value="投稿"/>
    </form>
{% endblock %}

templates/app/time_line.html
<div class="list-group">

    {% include 'app/tweet_box.html' %}
    {% if view_type == 'user_page' %}
        <div class="list-group-item load-area" id="load-area-{{ data.user.id }}">Load more</div>
    {% else %}
        <div class="list-group-item load-area with-following" id="load-area-{{ data.user.id }}">Load more</div>
    {% endif %}
</div>
<div class="modal" tabindex="-1" role="dialog" id="delete_modal" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">削除の確認</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div><!-- /.modal-header -->
            <div class="modal-body">
                <p>ツイートを削除しますか？</p>
            </div><!-- /.modal-body -->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                <button type="button" class="btn btn-primary" id="delete_button">削除</button>
            </div><!-- /.modal-footer -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<div class="modal" tabindex="-1" role="dialog" id="reply-modal" aria-labelledby="reply-modal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title username-header"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div><!-- /.modal-header -->
            <div class="modal-body">
                <h6 class="mb-2 text-muted"><a class="username" href="#">User</a>
                    - <span class="time"></span></h6>
                <p class="mb-2 tweet-content"></p>
            </div><!-- /.modal-body -->
            <div class="modal-footer reply-form">
                <form action="#" method="post">
                    <div class="form-row">
                        <div class="col">
                            {% csrf_token %}
                            <input class="form-control tweet-content-form" type="text" name="tweet_content" value="">
                        </div>
                        <div class="col-auto">
                            <span class="tweet-length align-bottom"></span>
                        </div>
                        <div class="col-auto">
                            <input class="btn btn-primary post-tweet" type="submit" value="ツイート">
                        </div>
                    </div>
                </form>
            </div><!-- /.modal-footer -->
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
{% if not data.user.is_authenticated %}
    <div class="modal" tabindex="-1" role="dialog" id="login_modal" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">ログイン</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div><!-- /.modal-header -->
                {#                <form method="POST" action="{% url 'login' %}">#}
                {#                    {% csrf_token %}#}

                <div class="modal-body">
                    <div class="alert alert-danger alert-dismissible collapse" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                                aria-hidden="true">&times;</span></button>
                        <span class="error-msg small"></span>
                    </div>
                    <div class="form-group">
                        <label for="username">ユーザーID</label>
                        <input class="form-control" type="text" name="username" id="username">
                    </div>
                    <div class="form-group">
                        <label for="password">パスワード</label>
                        <input class="form-control" type="password" name="password" id="password">
                    </div>
                </div><!-- /.modal-body -->
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">閉じる</button>
                    <button type="button" class="btn btn-primary" id="login_button">ログイン</button>
                </div><!-- /.modal-footer -->
                {#                </form>#}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
{% endif %}
<script type="text/javascript">
    var first_tweet = "{{ data.tweets.0.tweet.created_at|date:'Y-m-j H:i:s' }}";
</script>

templates/app/tweet_box.html
{% for item in data.tweets %}
    <div class="list-group-item timeline">
        <div class="user-avatar"><img src="/media/{{ item.user.setting.picture }}" class="avatar-img" alt=""></div>
        <div class="tweet-body" id="{{ item.tweet.id }}">
            <div class="tweet-id" hidden>{{ item.tweet.id }}</div>
            {% if item.is_rt == True %}
                <div class="rt-header small">
                    {{ item.rt_by.viewname }}さんがリツイート
                </div>
            {% endif %}
            <h6 class="mb-2 text-muted"><a
                    href="{% url 'app:user_page' item.user.username %}">{{ item.user.viewname }} @{{ item.user.username }}</a>
                - <a href="/detail/{{ item.tweet.id }}">{{ item.tweet.created_at|date:"Y/m/j H:i:s" }}</a></h6>
            <p class="mb-2 tweet-content">{{ item.tweet.content|linebreaksbr }}</p>
            {% if item.user.id == data.login_user.id %}
                <div class="tweet-footer-box">
                    <i class="far fa-trash-alt" data-toggle="modal" data-target="#delete_modal"
                       data-tweetid="{{ item.tweet.pk }}"></i>
                </div>
            {% endif %}
            {% if item.user.id != data.login_user.id %}
                <div class="tweet-footer-box">
                    {% if data.login_user.is_authenticated %}
                        <i class="far fa-comment" data-toggle="modal" data-target="#reply-modal"
                           data-tweetid="{{ item.tweet.pk }}"
                           data-reply-to-username="{{ item.user.username }}"></i>
                    {% else %}
                        <i class="far fa-comment" data-toggle="modal" data-target="#login_modal"></i>
                    {% endif %}
                </div>
                <div class="tweet-footer-box">
                    {% if data.login_user.is_authenticated %}
                        {% if item.rt_by == data.login_user %}
                            <i class="fas fa-retweet rt retweeted auth"></i>
                            <span class="rt-count">{% if item.rt_count != 0 %}{{ item.rt_count }}{% endif %}</span>
                        {% else %}
                            <i class="fas fa-retweet rt auth"></i>
                            <span class="rt-count">{% if item.rt_count != 0 %}{{ item.rt_count }}{% endif %}</span>
                        {% endif %}
                    {% else %}
                        <i class="fas fa-retweet rt" data-toggle="modal" data-target="#login_modal"></i>
                        <span class="rt-count">{% if item.rt_count != 0 %}{{ item.rt_count }}{% endif %}</span>
                    {% endif %}
                </div>
                <div class="tweet-footer-box">
                    {% if data.login_user.is_authenticated %}
                        {% if item.is_faved_by_user == True %}
                            <i class="fas fa-heart fav auth checked"></i>
                            <span class="fav-count">{{ item.fav_count }}</span>
                        {% else %}
                            <i class="far fa-heart fav auth"></i>
                            <span class="fav-count">{% if item.fav_count != 0 %}{{ item.fav_count }}{% endif %}</span>
                        {% endif %}
                    {% else %}
                        <i class="far fa-heart fav" data-toggle="modal" data-target="#login_modal"></i>
                    {% endif %}
                </div>
            {% endif %}
        </div>

    </div>
{% endfor %}

templates/app/tweet_form.html
<div class="card mb-2">
    <div class="card-body">
        <form class="tweet-form condensed" action="{% url 'app:post_tweet' %}" method="post">
            <div class="form-row">
                <div class="col">
                    {% csrf_token %}
                    <div>
                        <div class="form-control tweet-content-form" role="textbox" contenteditable="true"
                             aria-multiline="true" spellcheck="true" aria-expanded="false"
                             aria-owns="typeahead-dropdown-10" dir="ltr" data-placeholder="いまどうしてる？"
                             aria-autocomplete="list">
                            <div>いまどうしてる？</div>
                        </div>
                        <div class="editor-right editor-bottom">
                            <span class="tweet-length">140</span>

                        </div>
                    </div>

                </div>
            </div>
            <div class="form-row form-footer mt-2">
                <div class="col">
                    <input class="btn btn-primary post-tweet float-right" type="button" value="ツイート">
                </div>
            </div>
        </form>
    </div>

</div>

templates/app/user.html
{% extends "app/base.html" %}
{% load static %}

{% block left-column %}
    <div class="card">
        <ul>
            <li>
                {{ data.user.username }}
            </li>
            {% if data.login_user != data.user %}
                {% if not data.is_followed_by_login_user %}
                    <li>
                        <div class="user-id" hidden>{{ data.user.id }}</div>
                        <button class="follow-button">フォローする</button>
                    </li>
                {% else %}
                    <li>
                        <div class="user-id" hidden>{{ data.user.id }}</div>
                        <button class="follow-button followed">フォロー解除</button>
                    </li>
                {% endif %}
            {% endif %}
            <li>
                フォローしている： {{ data.cnt_following }}
            </li>
            <li>
                フォローされている： {{ data.cnt_followed }}
            </li>
        </ul>

    </div>
{% endblock %}

{% block body %}
    {% include 'app/time_line.html' %}
{% endblock %}